/* Private applicant chat. The only browser credential is this visitor's random conversation token. */
(()=>{
 const copy={
 en:['Your conversation','Team replies appear here automatically. Replies may take a minute or longer.','You','Transfer team','Send message','Write a message…','Saved · waiting for Discord delivery','Sent to the team','Checking for replies…','Unable to connect. Your message is still here; try again.','Your chat is saved in this browser. Keep using this browser to return.','New reply','Enter your player name and server to start.','Message the transfer team here. Your conversation is saved and shared with the transfer team in Discord.','Reply here','Private conversation'],
 es:['Tu conversación','Las respuestas aparecen automáticamente. Pueden tardar un minuto o más.','Tú','Equipo de traslado','Enviar mensaje','Escribe un mensaje…','Guardado · pendiente de entrega a Discord','Enviado al equipo','Buscando respuestas…','No se pudo conectar. Tu mensaje sigue aquí; inténtalo de nuevo.','El chat se guarda en este navegador. Usa este mismo navegador para volver.','Nueva respuesta','Introduce tu nombre de jugador y servidor para empezar.','Escribe al equipo aquí. La conversación se guarda y se comparte con el equipo en Discord.','Responde aquí','Conversación privada'],
 pt:['Sua conversa','As respostas aparecem automaticamente. Podem levar um minuto ou mais.','Você','Equipe de transferência','Enviar mensagem','Escreva uma mensagem…','Salvo · aguardando envio ao Discord','Enviado à equipe','Verificando respostas…','Não foi possível conectar. Sua mensagem continua aqui; tente novamente.','O chat fica salvo neste navegador. Use o mesmo navegador para voltar.','Nova resposta','Informe seu nome de jogador e servidor para começar.','Fale com a equipe aqui. A conversa é salva e compartilhada com a equipe no Discord.','Responda aqui','Conversa privada'],
 fr:['Votre conversation','Les réponses apparaissent automatiquement. Cela peut prendre une minute ou plus.','Vous','Équipe de transfert','Envoyer','Écrivez un message…','Enregistré · en attente d’envoi à Discord','Envoyé à l’équipe','Recherche de réponses…','Connexion impossible. Votre message est conservé ici ; réessayez.','Cette conversation est enregistrée dans ce navigateur. Revenez avec le même navigateur.','Nouvelle réponse','Saisissez votre nom de joueur et votre serveur pour commencer.','Contactez l’équipe ici. La conversation est enregistrée et partagée avec l’équipe sur Discord.','Répondez ici','Conversation privée'],
 de:['Dein Gespräch','Antworten erscheinen automatisch. Dies kann eine Minute oder länger dauern.','Du','Transferteam','Nachricht senden','Nachricht schreiben…','Gespeichert · wartet auf Discord-Zustellung','An das Team gesendet','Antworten werden gesucht…','Keine Verbindung. Deine Nachricht bleibt hier; versuche es erneut.','Der Chat wird in diesem Browser gespeichert. Verwende ihn auch bei deiner Rückkehr.','Neue Antwort','Gib zuerst deinen Spielernamen und Server ein.','Schreibe dem Team hier. Das Gespräch wird gespeichert und mit dem Team auf Discord geteilt.','Hier antworten','Privates Gespräch'],
 vi:['Cuộc trò chuyện của bạn','Phản hồi tự động xuất hiện. Có thể mất một phút hoặc lâu hơn.','Bạn','Đội chuyển máy chủ','Gửi tin nhắn','Nhập tin nhắn…','Đã lưu · đang chờ gửi tới Discord','Đã gửi cho đội','Đang kiểm tra phản hồi…','Không thể kết nối. Tin nhắn vẫn ở đây; hãy thử lại.','Trò chuyện được lưu trong trình duyệt này. Hãy dùng lại trình duyệt này khi quay lại.','Phản hồi mới','Nhập tên người chơi và máy chủ để bắt đầu.','Nhắn cho đội tại đây. Cuộc trò chuyện được lưu và chia sẻ với đội trên Discord.','Trả lời tại đây','Trò chuyện riêng tư'],
 ko:['내 대화','답변이 자동으로 표시됩니다. 1분 이상 걸릴 수 있습니다.','나','이전 담당팀','메시지 보내기','메시지를 입력하세요…','저장됨 · Discord 전송 대기 중','담당팀에 전송됨','답변 확인 중…','연결할 수 없습니다. 메시지는 그대로 있으니 다시 시도하세요.','대화는 이 브라우저에 저장됩니다. 돌아올 때 같은 브라우저를 사용하세요.','새 답변','플레이어 이름과 서버를 입력해 주세요.','여기에서 담당팀에 문의하세요. 대화는 저장되며 Discord에서 담당팀과 공유됩니다.','여기에 답장','비공개 대화'],
 ar:['محادثتك','تظهر الردود تلقائيًا. قد يستغرق الرد دقيقة أو أكثر.','أنت','فريق الانتقال','إرسال رسالة','اكتب رسالة…','تم الحفظ · بانتظار الإرسال إلى Discord','تم الإرسال إلى الفريق','جارٍ البحث عن ردود…','تعذر الاتصال. رسالتك ما زالت هنا؛ حاول مجددًا.','تُحفظ المحادثة في هذا المتصفح. استخدم المتصفح نفسه عند العودة.','رد جديد','أدخل اسم اللاعب والخادم للبدء.','راسل الفريق هنا. تُحفظ المحادثة وتُشارك مع فريق الانتقال في Discord.','الرد هنا','محادثة خاصة']};
 const tr=n=>(copy[state.language]||copy.en)[n],key='join1616-private-chat-v1',panel=document.getElementById('question-panel'),fab=document.getElementById('question-fab');
 let session=null,enabled=false,busy=false,polling=false,timer=null,seen='',lastTouch=0,messages=[],pending=null;
 try{session=JSON.parse(localStorage.getItem(key)||'null');if(!/^chat-/.test(session?.conversationId||''))session=null;}catch(_){}
 const view=document.createElement('section');view.id='applicant-chat';view.hidden=true;view.innerHTML='<header class="chat-heading"><div><small data-chat-private></small><h2 data-chat-title></h2></div><button type="button" data-chat-close aria-label="Close">×</button></header><p class="chat-hint" data-chat-hint></p><div class="chat-messages" role="log" aria-live="polite" aria-relevant="additions" aria-label="Conversation"></div><p class="chat-storage" data-chat-storage></p><label class="chat-compose-label" for="chat-compose" data-chat-label></label><textarea id="chat-compose" maxlength="1500" rows="2"></textarea><footer class="chat-compose-actions"><small role="status" data-chat-status></small><button type="button" data-chat-send></button></footer>';panel.append(view);
 const list=view.querySelector('.chat-messages'),input=view.querySelector('textarea'),status=view.querySelector('[data-chat-status]');
 const badge=document.createElement('span');badge.className='chat-unread';badge.hidden=true;fab.append(badge);
 function persist(){try{localStorage.setItem(key,JSON.stringify(session));}catch(_){}}
 function labels(){view.querySelector('[data-chat-title]').textContent=tr(0);view.querySelector('[data-chat-hint]').textContent=tr(1);view.querySelector('[data-chat-storage]').textContent=tr(10);view.querySelector('[data-chat-label]').textContent=tr(14);view.querySelector('[data-chat-private]').textContent=tr(15);input.placeholder=tr(5);view.querySelector('[data-chat-send]').textContent=tr(4);view.querySelector('[data-chat-close]').setAttribute('aria-label',t('closeGuide'));if(enabled){for(const name of ['questionPanelIntro','questionDiscordNote'])document.querySelectorAll('[data-i18n="'+name+'"]').forEach(e=>e.textContent=tr(13));}}
 function show(){if(!enabled||!session?.started)return;document.getElementById('question-form-view').hidden=true;document.getElementById('question-confirmation').hidden=true;view.hidden=false;labels();badge.hidden=true;seen=messages.filter(m=>m.direction==='team').at(-1)?.id||seen;}
 function render(data){const next=data.messages||[],nearBottom=list.scrollHeight-list.scrollTop-list.clientHeight<70,oldIds=new Set(messages.map(m=>m.id));messages=next;
 const changed=list.dataset.signature!==JSON.stringify(next);if(changed){list.replaceChildren();for(const m of next){const row=document.createElement('article');row.className='chat-message '+(m.direction==='team'?'team':'applicant');const meta=document.createElement('small');meta.textContent=(m.direction==='team'?(m.author||tr(3)):tr(2))+' · '+new Date(m.createdAt).toLocaleTimeString(state.language,{hour:'2-digit',minute:'2-digit'});const text=document.createElement('p');text.textContent=m.text;row.append(meta,text);if(m.direction==='applicant'){const delivery=document.createElement('small');delivery.textContent=m.delivered?tr(7):tr(6);row.append(delivery);}list.append(row);}list.dataset.signature=JSON.stringify(next);if(nearBottom)list.scrollTop=list.scrollHeight;}
 if(!panel.hidden){seen=next.filter(m=>m.direction==='team').at(-1)?.id||seen;badge.hidden=true;}else if(next.some(m=>m.direction==='team'&&m.id!==seen&&!oldIds.has(m.id))){badge.textContent=tr(11);badge.hidden=false;}
 }
 async function api(action,extra={}){return sendToGoogleSheets({requestType:action,...session,...extra,website:''});}
 async function poll(){if(!enabled||!session?.started||polling||document.hidden)return;polling=true;try{const action=!panel.hidden&&Date.now()-lastTouch>60000?'chat.touch':'chat.poll';const result=await api(action);if(action==='chat.touch')lastTouch=Date.now();render(result);if(!busy)status.textContent='';}catch(_){status.textContent=tr(9);}finally{polling=false;}}
 function schedule(){clearTimeout(timer);timer=setTimeout(async()=>{await poll();schedule();},panel.hidden?60000:15000);}
 const originalOpen=openQuestionPanel;openQuestionPanel=function(){originalOpen();if(enabled&&session?.started){show();poll();}schedule();};
 view.querySelector('[data-chat-close]').onclick=()=>{closeQuestionPanel();view.hidden=true;};
 const originalSubmit=submitQuestion;document.getElementById('question-submit').removeEventListener('click',originalSubmit);
 document.getElementById('question-submit').addEventListener('click',async()=>{
 if(!enabled){originalSubmit();return;}if(busy)return;
 const question=document.getElementById('question-message').value.trim(),username=document.getElementById('question-prefill-username').value.trim(),currentServer=document.getElementById('question-prefill-server').value.trim(),category=document.getElementById('question-category').value,error=document.getElementById('question-error');
 if(!username||!currentServer||!category||!question){error.textContent=tr(12);error.hidden=false;return;}
 if(!session){session={conversationId:'chat-'+crypto.randomUUID(),chatToken:crypto.randomUUID()+crypto.randomUUID()};persist();}
 const button=document.getElementById('question-submit');busy=true;button.disabled=true;error.hidden=true;
 const fingerprint=question+'|'+username+'|'+currentServer;if(!pending||pending.fingerprint!==fingerprint)pending={fingerprint,id:crypto.randomUUID()};
 try{const result=await api('chat.start',{messageId:pending.id,username,currentServer,alliance:document.getElementById('question-prefill-alliance').value.trim(),category,question,language:state.language,confirmationCode:state.confirmationCode||''});pending=null;session.started=true;persist();document.getElementById('question-message').value='';show();render(result);schedule();}catch(_){error.textContent=tr(9);error.hidden=false;}finally{busy=false;button.disabled=false;}
 });
 view.querySelector('[data-chat-send]').onclick=async()=>{const question=input.value.trim();if(!question||busy||!session)return;busy=true;const button=view.querySelector('[data-chat-send]');button.disabled=true;if(!pending||pending.fingerprint!==question)pending={fingerprint:question,id:crypto.randomUUID()};status.textContent=tr(8);try{const result=await api('chat.send',{question,messageId:pending.id});pending=null;input.value='';render(result);status.textContent=tr(6);}catch(_){status.textContent=tr(9);}finally{busy=false;button.disabled=false;}};
 const originalLanguage=setLanguage;setLanguage=function(lang){originalLanguage(lang);labels();};
 async function ready(){try{const result=await sendToGoogleSheets({requestType:'chat.ready',website:''});enabled=!!result.enabled;labels();if(enabled&&session){await poll();schedule();}}catch(_){enabled=false;}}
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});
 // Link this browser conversation only after proving possession of an application code.
 const originalLoad=loadExistingApplication;loadExistingApplication=async function(){await originalLoad();if(enabled&&session&&state.confirmationCode)api('chat.link',{confirmationCode:state.confirmationCode}).catch(()=>{});};document.getElementById('lookup-application').onclick=loadExistingApplication;
 window.Join1616Chat={ready,linkApplication(){if(enabled&&session?.started&&state.confirmationCode)return api('chat.link',{confirmationCode:state.confirmationCode}).catch(()=>{});}};ready();
})();
